Acoustics module update
sandialabs/seat-qgis-plugin pull request #34
Opened 2024-06-26 20:27 UTC by tnelson-integral

Start of Acoustics Module update for weighting and exposure level.

2024-06-26 20:28 UTC, tnelson-integral commented
Just starting this. Still have work to do on updating the calculations, but this will be the next large update.

2024-09-04 20:39 UTC, tnelson-integral commented
Ashley is continuing to update the documents for the Acoustics section, however the code is ready for review.

2024-09-04 22:03 UTC, ssolson commented
Thanks for the heads up @tnelson-integral . Before we review you need to merge the main branch into this branch so everything is up to date. Currently this branch conflicts with the main. After merging most likely you will need to make changes to ensure we are passing tests. Lastly it would be best to add Acoustics modules tests before merging if we are not on a short time turn around for this.

2024-09-13 20:06 UTC, tnelson-integral commented
All but 1 linting issue fixed. I need to figure out how to remove or merge 2 more defs.

2024-09-16 15:56 UTC, ssolson commented
Great job Tim 🎉! I'll start reviewing.

2024-09-16 18:01 UTC, tnelson-integral commented
Hi Sterling,
It is possible I might have broken a few things while getting it formatted (Hopefully not though). I plan to look at this again Tuesday. If you haven't started yet, hold off, and I will let you know once I have verified everything still works.
-Thanks,
-Tim

Tim Nelson (he/him/his) | Project Scientist
Tel: 561.240.5096 | Cell: 803.319.3344 | St. Petersburg | FL
***@***.*** | Bio<https://www.integral-corp.com/staff/timothy-r-nelson-ph-d>

<https://www.integral-corp.com/>[cid:integral_1a04a855-2877-4c4f-bd98-b89de3950d0f.png]<https://www.integral-corp.com/>

________________________________
From: ssolson ***@***.***>
Sent: Monday, September 16, 2024 11:56 AM
To: sandialabs/seat-qgis-plugin ***@***.***>
Cc: Tim Nelson ***@***.***>; Mention ***@***.***>
Subject: Re: [sandialabs/seat-qgis-plugin] Acoustics module update (PR #34)

[CAUTION: External email. Think before you click links or open attachments.]

Great job Tim 🎉! I'll start reviewing.

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sandialabs_seat-2Dqgis-2Dplugin_pull_34-23issuecomment-2D2353310927&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=tqlGmmd8SaD4ZxlV1H2Iu-CEmR7hobvLtCU1bjRy2e_Xx8gmee1jwi7FCP9DCatw&s=2dvP_0fuftUe8o7j43OnWXJxlP_gnKP-_YrDegCYBjQ&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AZARDBI7AJHBAQWZZMT4EB3ZW35TRAVCNFSM6AAAAABJ6TD5U2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNJTGMYTAOJSG4&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=tqlGmmd8SaD4ZxlV1H2Iu-CEmR7hobvLtCU1bjRy2e_Xx8gmee1jwi7FCP9DCatw&s=0l2deISz6A95BrtHvV-ODpK-7NtOMPh8D-TgGpUsZyg&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-09-18 22:47 UTC, tnelson-integral commented
@ssolson were you able to create a .zip file and get it to seat to load and run correctly. I am having problems installing the plugin and I am not sure if it with my QGIS install or the seat package.

2024-09-19 16:18 UTC, ssolson commented
> @ssolson were you able to create a .zip file and get it to seat to load and run correctly. I am having problems installing the plugin and I am not sure if it with my QGIS install or the seat package.

@tnelson-integral  I started looking at this an hour ago. The easy problem to fix is in `stressor_receptor_calc.py` changing 
    `def init_gui(self) -> None:`
to
   `def initGui(self) -> None:`
   
I am not sure why the GUI expects camelCase but we need to add a pylint ignore to this.

Once I make that change I can install the package but it will fail to open the first time. If I click it again the package will open. If I try to load input the package will fail again.  I have not been able to track down the issue behind this.

2024-09-25 14:14 UTC, ssolson commented
@tnelson-integral I fixed the installation issues in https://github.com/IntegralEnvision/seat-qgis-plugin/pull/17

But I am having trouble with the tutorials. Did the cases change/ is there a new shared Drive?

2024-09-25 14:21 UTC, tnelson-integral commented
@ssolson There is a new set of files for the tutorial. I just sent you the invite to the files. Probably an enhancement for a future time is to allow .ini files with missing fields.
-Tim

2024-09-25 15:20 UTC, ssolson commented
> @ssolson There is a new set of files for the tutorial. I just sent you the invite to the files. Probably an enhancement for a future time is to allow .ini files with missing fields. -Tim

All the default files in the Tanana river folder have been deleted and replace with aelleson .ini file paths.

2024-09-25 15:26 UTC, ssolson commented
> @ssolson Should be updated now

Same problem with the style files. 

Could you just confirm that you can get the tutorials to work and update the files as needed?

2024-09-25 17:38 UTC, tnelson-integral commented
@ssolson Everything should be updated and working.

2024-09-26 14:59 UTC, ssolson commented
> @ssolson Everything should be updated and working with the recent changes.

Tim I don't know how this is working for you.

![image](https://github.com/user-attachments/assets/38156af5-3b25-42dd-9dac-817370b1cd8c)

`style_layer` takes a path not a dataframe.

![image](https://github.com/user-attachments/assets/af88edd2-e696-48ac-8716-aed914f53784)

Again, could you just confirm that you can get the tutorials to work and update the files as needed?

2024-09-26 22:13 UTC, tnelson-integral commented
I can get everything to run with the last change.

2024-10-30 16:05 UTC, ssolson requested changes
Tim apologies for my delayed review on this from the Hurricane/ Conference. I am finally catching up on everything. I am having a couple of issues/ questions with this module:

I think most importantly we need to address the crashing of QGIS/ SEAT and make sure the example results are up to date in the documentation. I am not going to address all the coding issues due to budget constraints.

SEAT causes QGIS to crash if:
1. If I click "weighting" or "Acoustic Metric" before anything else
2. If I type a non numeric value into "Acoustic Threshold Value"
3. If I run the acoustics module via a Load GUI then click the SEAT plugin again to run a different simulation
   
SEAT will crash:
1. If I click Save GUI Inputs then cancel

Tanana River Issues
1. After running the Tanana river example I cannot see the QuickMapService 
  a. QuickMap will work before running the Tanana River example
  b. QuickMap works on the Pacwave Example
  c. Can you see QuickMap after running the example?

Pacwave Issues
1. The Acoustics Results in PacWave example 
  a. The Results are unruly due to the results being shown for 14 Sea-states. Anyway you can think of to simplify?
  b.  Most of the results are a single solid color. Is this the correct output?
  c. It looks like you guys updated the acoustics documentation inputs but not the outputs. Can you update the outputs you expect so I can be sure I am matching. Currently mine are very different from the previous results.
  d. This example is really slow now on the order of 5 minutes to run. Is this expected?

2024-10-31 15:04 UTC, tnelson-integral commented
Hi Sterling,
Thanks for the feedback. Unfortunately, for the acoustics all those need to be generated for a complete analysis. I could further sort those in groups, so they are easier to sort through. Alternatively, I can add a checkbox to select whether to run the probabilistic and/or nonprobabilitic. I will talk with Sam regarding availability for me to work on these issues.
-Tim


Tim Nelson (he/him/his) | Project Scientist
Tel: 561.240.5096 | Cell: 803.319.3344 | St. Petersburg | FL
***@***.*** | Bio<https://www.integral-corp.com/staff/timothy-r-nelson-ph-d>

<https://www.integral-corp.com/>[cid:integral_1a04a855-2877-4c4f-bd98-b89de3950d0f.png]<https://www.integral-corp.com/>

________________________________
From: ssolson ***@***.***>
Sent: Wednesday, October 30, 2024 12:06 PM
To: sandialabs/seat-qgis-plugin ***@***.***>
Cc: Tim Nelson ***@***.***>; Mention ***@***.***>
Subject: Re: [sandialabs/seat-qgis-plugin] Acoustics module update (PR #34)

[CAUTION: External email. Think before you click links or open attachments.]

@ssolson requested changes on this pull request.

Tim apologies for my delayed review on this from the Hurricane/ Conference. I am finally catching up on everything. I am having a couple of issues/ questions with this module:

I think most importantly we need to address the crashing of QGIS/ SEAT and make sure the example results are up to date in the documentation. I am not going to address all the coding issues due to budget constraints.

SEAT causes QGIS to crash if:

 1.  If I click "weighting" or "Acoustic Metric" before anything else
 2.  If I type a non numeric value into "Acoustic Threshold Value"
 3.  If I run the acoustics module via a Load GUI then click the SEAT plugin again to run a different simulation

SEAT will crash:

 1.  If I click Save GUI Inputs then cancel

 2.  After running the Tanana river example I cannot see the QuickMapService
a. QuickMap will work before running the Tanana River example
b. QuickMap works on the Pacwave Example
c. Can you see QuickMap after running the example?

 3.  The Acoustics Results in PacWave example
a. The Results are unruly due to the results being shown for 14 Sea-states. Anyway you can think of to simplify?
b. Most of the results are a single solid color. Is this the correct output?
c. It looks like you guys updated the acoustics documentation inputs but not the outputs. Can you update the outputs you expect so I can be sure I am matching. Currently mine are very different from the previous results.
d. This example is really slow now on the order of 5 minutes to run. Is this expected?

________________________________

In seat/stressor_receptor_calc.py<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sandialabs_seat-2Dqgis-2Dplugin_pull_34-23discussion-5Fr1750531253&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=lsXhRFpP1M9mE18WC7A670ziY01dpNCR8Hm6CJmz7gabPN74G_YkNcrlLjKg1JQ9&s=sYF2giaeLDJahpmFezpM-KZRNbk36CMhjR4Ka7JM4H8&e=>:

> @@ -386,15 +385,25 @@ def select_and_load_in(self) -> None:
             self.test_exists(self.dlg.paracousti_device_not_present, fin, "Directory")
             fin = config.get("Input", "paracousti probabilities file")
             self.test_exists(self.dlg.paracousti_probabilities_file, fin, "File")
-            fin = config.get("Input", "paracousti threshold file")
-            self.test_exists(self.dlg.paracousti_threshold_file, fin, "File")


One of the tests is failing because you paracousti_threshold_value no longer comes from a file so we do not check for file existence any longer

________________________________

In docs/src/seat_qgis_plugin/acoustics/01_paracousti_preprocessing.rst<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sandialabs_seat-2Dqgis-2Dplugin_pull_34-23discussion-5Fr1822811651&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=lsXhRFpP1M9mE18WC7A670ziY01dpNCR8Hm6CJmz7gabPN74G_YkNcrlLjKg1JQ9&s=lYg_E0y869IhMA73odQFuJ4S8LUGqMFNepWn3dX_tjE&e=>:

> @@ -0,0 +1,38 @@
+.. _01_paracousti_preprocessing:
+Paracousti Pre-Processing
+-------------------------
+Several metrics can be calculated from ParAcousti output that are useful in determining impacts to marine species. These include the weighted and unweighted sound pressure level (SPL) and sound exposure level (SEL). Due to the resource and time-intensive calculations, a stand-alone python routine is included within the SEAT package. This routine calculates the user selected metrics and weights form the existing Paracousti metrics. The calculated metrics are saved to a netcdf variable with the same dimensions as the original Paracousti netcdf.


form => from

________________________________

In docs/src/seat_qgis_plugin/acoustics/01_paracousti_preprocessing.rst<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sandialabs_seat-2Dqgis-2Dplugin_pull_34-23discussion-5Fr1822814058&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=lsXhRFpP1M9mE18WC7A670ziY01dpNCR8Hm6CJmz7gabPN74G_YkNcrlLjKg1JQ9&s=51ypySjTsX057yfIQ6To593caM1TUrx84oUb0jmzCoI&e=>:

> +To run the Paracousti pre-processing routine,
+
+.. code-block:: python
+
+    from utils import paracousti_fxns
+    paracousti_path  = r'./Path/to/Paracousti/netCDF'
+    save_path = r'./Path/to/save/updated/netCDF'
+    calc_paracousti_metrics(paracousti_path, save_path, weights="All")


This is really unclear on top of being a disjointed user experience. These functions should be accessible from the normal Paracousti or SEAT workflow, not some in between random function.

There is no budget to fix this at this point so going with this version:

For this to work the user will need to activate their qgis python environment. That has to be mentioned.

Is the paracousti_path and save_path above a file or a folder?

It is unclear to me if this is required to use the SEAT acoustics modules or not. Do I always need to run this pre-processing routine?

________________________________

In docs/src/seat_qgis_plugin/acoustics/02_inputs.rst<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sandialabs_seat-2Dqgis-2Dplugin_pull_34-23discussion-5Fr1822881265&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=lsXhRFpP1M9mE18WC7A670ziY01dpNCR8Hm6CJmz7gabPN74G_YkNcrlLjKg1JQ9&s=YlDIiuQMeIYfmj3an8M2NSuaMBOAf4CmEfn5IvKQ27A&e=>:

> +^^^^^^^^^^^^^^^^^^^^^^
+
+The risk layer is a receptor file that serves as an additional input to each module and designates which layers are sensitive and would be affected by the acoustics. It must be a numerically classified .tif format, the same as what is used in the shear stress and velocity modules.
+
+.. figure:: ../../media/risk_layer_gui_input.webp
+   :scale: 100%
+   :alt: Risk Layer File
+
+   Represents a layer to evaluate change against. Examples include vegetation habitat, marine ecosystems, contaminated sediments, marine protected areas, or archaeological artifacts.
+
+- **File Type**: Supports geotiff (.tif) file format.
+
+  - **Geotiff Details**:
+    - Must have the same projection and datum as the model files.
+    - Will be nearest-neighbor interpolated to align with the model files' grid points (structured/unstructured).
+    - Must be integer classified, e.g., (0 = 'Kelp', 1 = 'Rock')


What about the "Depth Averaging" input?

________________________________

In docs/src/seat_qgis_plugin/acoustics/03_species_properties.rst<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sandialabs_seat-2Dqgis-2Dplugin_pull_34-23discussion-5Fr1822916881&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=lsXhRFpP1M9mE18WC7A670ziY01dpNCR8Hm6CJmz7gabPN74G_YkNcrlLjKg1JQ9&s=niS8ONP2sMDgM1rjrDxAp_4XJoQza-CF_9Z1RfrRYB4&e=>:

> +Depth Averaging
+^^^^^^^^^^^^^^^^
+
+The Depth Averaging drop  [...]

2024-10-31 15:10 UTC, ssolson commented
Tim your response is puzzling. I think you are replying to maybe the least important issue.

Most important:
- Using the SEAT version in this PR is causing QGIS to crash 
- The outputs to the documentation are outdated and I do not know what is correct.

2024-10-31 15:18 UTC, tnelson-integral commented
Hi Sterling,
I had lumped those into the issues comment and will talk with Sam regarding fixing the crashing bug fixes. I will also reach out to Ashely to see if she had an update to the documentation that didn't get merged. I am off tomorrow so it will be early next week before I am able to address some of these issures.  I will keep you updated.
-Thanks,
-Tim

Tim Nelson (he/him/his) | Project Scientist
Tel: 561.240.5096 | Cell: 803.319.3344 | St. Petersburg | FL
***@***.*** | Bio<https://www.integral-corp.com/staff/timothy-r-nelson-ph-d>

<https://www.integral-corp.com/>[cid:integral_1a04a855-2877-4c4f-bd98-b89de3950d0f.png]<https://www.integral-corp.com/>

________________________________
From: ssolson ***@***.***>
Sent: Thursday, October 31, 2024 11:11 AM
To: sandialabs/seat-qgis-plugin ***@***.***>
Cc: Tim Nelson ***@***.***>; Mention ***@***.***>
Subject: Re: [sandialabs/seat-qgis-plugin] Acoustics module update (PR #34)

[CAUTION: External email. Think before you click links or open attachments.]

Tim your response is puzzling. I think you are replying to maybe the least important issue.

Most important:

 *   Using the SEAT version in this PR is causing QGIS to crash
 *   The outputs to the documentation are outdated and I do not know what is correct.

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sandialabs_seat-2Dqgis-2Dplugin_pull_34-23issuecomment-2D2450130420&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=bWI1OMYrYEKRS77VrAhyhM7PXPR-znXBzOxKnImcczaj6XqeRcNYKrD_usnccKwg&s=52iTDfQP2GoaYefesOYfEDw1w570CYCqIrj_B0vlQi0&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AZARDBM423LXHNJXLAYGSETZ6JCA7AVCNFSM6AAAAABJ6TD5U2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINJQGEZTANBSGA&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=bWI1OMYrYEKRS77VrAhyhM7PXPR-znXBzOxKnImcczaj6XqeRcNYKrD_usnccKwg&s=wmqaWsg332DH_VwRhVdaXtV34eMACHA3GKeM2ugk1_E&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-11-08 20:10 UTC, tnelson-integral commented
This is still undergoing review. I will send you an email once this is ready.

2024-11-11 14:06 UTC, ssolson commented
Thanks Tim.

2024-11-20 22:17 UTC, anellenson commented on docs/src/seat_qgis_plugin/acoustics/02_inputs.rst
> +    - Must be integer classified, e.g., (0 = 'Kelp', 1 = 'Rock')
Added

2024-11-20 22:17 UTC, anellenson commented on docs/src/seat_qgis_plugin/acoustics/01_paracousti_preprocessing.rst
> +Several metrics can be calculated from ParAcousti output that are useful in determining impacts to marine species. These include the weighted and unweighted sound pressure level (SPL) and sound expos
changed

2024-11-20 22:19 UTC, anellenson commented on docs/src/seat_qgis_plugin/acoustics/01_paracousti_preprocessing.rst
> +    calc_paracousti_metrics(paracousti_path, save_path, weights="All")
Not sure how this workflow will go, either, but a requirements file is included above.
 Also added a note about when to run the pre-processing routine above.

2024-11-20 22:22 UTC, anellenson commented on docs/src/seat_qgis_plugin/acoustics/03_species_properties.rst
> +4. **Top Bin**: Value from top bin.
Removed from the docs

2024-11-20 22:22 UTC, anellenson commented on docs/src/tutorials/pacwave/acoustics.rst
> +    - `acoustics_module_SEL_LFC_199db_threshold.ini`: Sound exposure level for low frequency creteceans with a 199db threshold
Selected the first one and included the new images as output.

2024-11-20 22:22 UTC, anellenson commented on docs/src/tutorials/pacwave/acoustics.rst
> +   Your paths will differ than the ones shown in the example below. If you get an error double check the paths making sure, or make sure that the `.ini` files are pointing
done

2025-01-10 16:24 UTC, tnelson-integral commented
Hi Sterling,

The holidays were great. I hope you had a great holiday season too. I have updated the plugin to fix all bugs we could find internally, including adding another person at Integral to test. We made a few changes to the tutorial data, now having a deployed folder that works with the Main branch on GitHub. For the "in-development" branches, such as the Acoustics updates, the data is in a Development directory with subdirectories for active branches. I was still having trouble passing all the tests for the repository. I applied the black formatting plugin and ran it for each file, but still have a few issues. Due to function changes and variable renaming, some of the test scripts have likely broken. The documentation is mostly up to date. One last change we made was renaming "risk layer" to "area of interest," which has not been updated in the documentation. I believe we are going to discuss the documentation efforts in an upcoming meeting. On my end, the plugin works for me and Ashley. You are welcome to test it as well and please let me know if you run into any issues. There are new style files in the folder "Development/DEMO Files Tabbed GUI - Acoustics_AOI." I am going to resend links to the deployed and development folders to you in case the existing share was broken during reorganization.

-Tim


Tim Nelson (he/him/his) | Senior Scientist
Tel: 561.240.5096 | Cell: 803.319.3344 | St. Petersburg | FL
***@***.*** | Bio<https://www.integral-corp.com/staff/timothy-r-nelson-ph-d>

<https://www.integral-corp.com/>[cid:integral_1a04a855-2877-4c4f-bd98-b89de3950d0f.png]<https://www.integral-corp.com/>

________________________________
From: ssolson ***@***.***>
Sent: Friday, January 10, 2025 8:11 AM
To: sandialabs/seat-qgis-plugin ***@***.***>
Cc: Tim Nelson ***@***.***>; Mention ***@***.***>
Subject: Re: [sandialabs/seat-qgis-plugin] Acoustics module update (PR #34)

[CAUTION: External email. Think before you click links or open attachments.]

This is still undergoing review. I will send you an email once this is ready.

Hey @tnelson-integral<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tnelson-2Dintegral&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=Yn83XI9QZV7rQ_mUtW6CoZUSMmSwPyFFoLpXJDIGmB_gQitci6XYbPIEU_R2LsGJ&s=UT2hBifKl937tUR2WTmJhUDXhqEcywI5PO_T5vqFMN4&e=> I hope you had great holidays. How are we doing over here and do you need any help?

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sandialabs_seat-2Dqgis-2Dplugin_pull_34-23issuecomment-2D2582683911&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=Yn83XI9QZV7rQ_mUtW6CoZUSMmSwPyFFoLpXJDIGmB_gQitci6XYbPIEU_R2LsGJ&s=u3scYytRsZE2W7-7zr5no_yZCt75SqyEADTRCCMCPMc&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AZARDBNMLY5IPNL5IEBEXKD2J7BJLAVCNFSM6AAAAABJ6TD5U2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKOBSGY4DGOJRGE&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=Yn83XI9QZV7rQ_mUtW6CoZUSMmSwPyFFoLpXJDIGmB_gQitci6XYbPIEU_R2LsGJ&s=1mSYH1RrfBZrWtrCHY_c_pKTgb8IrlMgfhxDrPlFowM&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2025-01-22 16:47 UTC, tnelson-integral commented on seat/stressor_receptor_calc.py
> -            self.test_exists(self.dlg.paracousti_threshold_file, fin, "File")
done

2025-02-03 15:49 UTC, tnelson-integral commented
Hi @ssolson. Everything is updated on our end. Let us know if you have any other recommendations.  -Tim

2025-02-03 16:15 UTC, ssolson commented
> Hi @ssolson. Everything is updated on our end. Let us know if you have any other recommendations. -Tim
Thanks Tim. I'll take a look this week.

2025-02-04 16:02 UTC, ssolson commented
@tnelson-integral 

Why have you created a "seat-qgis-plugin[]" folder in addition to the "seat" folder? There should only be one folder and the canonical folder is "seat".

Please update all of the changes you are proposing into the correct folder. Please be careful to  only update your changes into the correct folder. I am worried you are working off some old files and I am going to have to redo all the linting work I did if you simply copy paste one folder into the other. 

Why are you trying to commit 3 different zip files to the main?

2025-02-04 16:25 UTC, tnelson-integral commented
Hi Sterling,
The seat-qgis-plugin[] folder appears to have been committed on Jan 21st, after all code changes were completed in "seat". I removed the zip files which seem to have been committed by accident. I will remove the seat-qgis-plugin[] folder after talking with Ashley and then commit all changes.
-Tim


Tim Nelson (he/him/his) | Senior Scientist
Tel: 561.240.5096 | Cell: 803.319.3344 | St. Petersburg | FL
***@***.*** | Bio<https://www.integral-corp.com/staff/timothy-r-nelson-ph-d>

<https://www.integral-corp.com/>[cid:integral_1a04a855-2877-4c4f-bd98-b89de3950d0f.png]<https://www.integral-corp.com/>

________________________________
From: ssolson ***@***.***>
Sent: Tuesday, February 4, 2025 11:02 AM
To: sandialabs/seat-qgis-plugin ***@***.***>
Cc: Tim Nelson ***@***.***>; Mention ***@***.***>
Subject: Re: [sandialabs/seat-qgis-plugin] Acoustics module update (PR #34)

[CAUTION: External email. Think before you click links or open attachments.]

@tnelson-integral<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tnelson-2Dintegral&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=_mDScRxtdSR_wXDOXggN2wUPNsS5NIGNm2EJG2BUHrC5RwPD2UP0MQJa4fdURKhF&s=q9_hyA94ARUGe3Kl_jSRVxWmTfvEHUEnfenXp_dJpkI&e=>

Why have you created a "seat-qgis-plugin[]" folder in addition to the "seat" folder? There should only be one folder and the canonical folder is "seat".

Please update all of the changes you are proposing into the correct folder. Please be careful to only update your changes into the correct folder. I am worried you are working off some old files and I am going to have to redo all the linting work I did if you simply copy paste one folder into the other.

Why are you trying to commit 3 different zip files to the main?

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sandialabs_seat-2Dqgis-2Dplugin_pull_34-23issuecomment-2D2634410397&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=_mDScRxtdSR_wXDOXggN2wUPNsS5NIGNm2EJG2BUHrC5RwPD2UP0MQJa4fdURKhF&s=G78_Be2_gXv6A_doETvDOUArWTdbiYbDpcugvqu5-a8&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AZARDBMEPWFZLNW7CH7EVET2ODQDDAVCNFSM6AAAAABJ6TD5U2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMMZUGQYTAMZZG4&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=_mDScRxtdSR_wXDOXggN2wUPNsS5NIGNm2EJG2BUHrC5RwPD2UP0MQJa4fdURKhF&s=AD3iHHHPZ31xwL-kxDUCTzlAaxU5x2TJLvn9ayCADpo&e=>.
You are receiving this because you were mentioned.

2025-02-04 16:29 UTC, ssolson commented
Fantastic. Thanks Tim.

2025-02-04 19:57 UTC, tnelson-integral commented
Hi Sterling,
The directory and zip files have been removed. I recreated the plugin and verified it works after these were removed. Please let me know if you come across anything else that needs to be addressed.
-Thanks,
-Tim


Tim Nelson (he/him/his) | Senior Scientist
Tel: 561.240.5096 | Cell: 803.319.3344 | St. Petersburg | FL
***@***.*** | Bio<https://www.integral-corp.com/staff/timothy-r-nelson-ph-d>

<https://www.integral-corp.com/>[cid:integral_1a04a855-2877-4c4f-bd98-b89de3950d0f.png]<https://www.integral-corp.com/>

________________________________
From: ssolson ***@***.***>
Sent: Tuesday, February 4, 2025 11:29 AM
To: sandialabs/seat-qgis-plugin ***@***.***>
Cc: Tim Nelson ***@***.***>; Mention ***@***.***>
Subject: Re: [sandialabs/seat-qgis-plugin] Acoustics module update (PR #34)

[CAUTION: External email. Think before you click links or open attachments.]

Fantastic. Thanks Tim.

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sandialabs_seat-2Dqgis-2Dplugin_pull_34-23issuecomment-2D2634480477&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=thTbrnfFYyvzQzfSu-ewQFpjMWIC2YeQ8A8kznmSm94zvlrqn_sua6mCcZ1m4JdL&s=SULwkuiYH8xCUpWnx1FZK67WALQZR2N3R8aYcUi5y54&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AZARDBK7EG7V75SWH4PQI7T2ODTGLAVCNFSM6AAAAABJ6TD5U2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMMZUGQ4DANBXG4&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=thTbrnfFYyvzQzfSu-ewQFpjMWIC2YeQ8A8kznmSm94zvlrqn_sua6mCcZ1m4JdL&s=fSmYzc7QHwCEsbqLLuuaAn81YIcqE5jQBFmwC32aUuw&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2025-02-11 14:34 UTC, ssolson commented on seat/paracousti_pre_process_routine.py
> +save_directory = r"C:\Users\aellenson\OneDrive - Integral Consulting Inc\C1308 Sandia\Tutorial_Files\Development\DEMO Files Tabbed GUI - Acoustics\pacwave\paracousti_files_with_metrics_TU\\"
Tim what do you think the best way to clean this up would be?

We shouldn't be pushing hardcoded local paths into a public tool.

2025-02-11 14:41 UTC, ssolson commented on seat/paracousti_pre_process_routine.py
> +save_directory = r"C:\Users\aellenson\OneDrive - Integral Consulting Inc\C1308 Sandia\Tutorial_Files\Development\DEMO Files Tabbed GUI - Acoustics\pacwave\paracousti_files_with_metrics_TU\\"
What do you think about setting up the file to take sysargs?

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ParAcousti pre-processing routine.

This module processes parAcousti files, which can be resource intensive depending on
grid resolution and weights selected. Processing may take several hours to complete.

Required packages:
    - xarray with netCDF4 (pip install "xarray[io]")
    - scipy (included with xarray[io])
    - tqdm (pip install tqdm)
"""

import argparse
from pathlib import Path
from . import utils.paracousti_fxns as paracousti_fxns


def process_paracousti_files(input_dir: str, output_dir: str, weights: str = "TU") -> bool:
    """
    Process parAcousti files and calculate metrics.

    Args:
        input_dir: Directory containing parAcousti files
        output_dir: Directory to save processed files
        weights: Weight type to use ("TU" or "All")

    Returns:
        bool: True if processing successful, False otherwise
    """
    input_path = Path(input_dir)
    output_path = Path(output_dir)
    
    if not input_path.exists():
        raise FileNotFoundError(f"Input directory not found: {input_dir}")
    
    output_path.mkdir(parents=True, exist_ok=True)
    
    return paracousti_fxns.calc_paracousti_metrics(
        str(input_path),
        str(output_path),
        weights=weights
    )

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Process parAcousti files.')
    parser.add_argument('input_dir', help='Directory containing parAcousti files')
    parser.add_argument('output_dir', help='Directory to save processed files')
    parser.add_argument('--weights', default="TU", choices=['TU', 'All'],
                      help='Weight type to use (default: TU)')
    
    args = parser.parse_args()
    
    try:
        status = process_paracousti_files(
            args.input_dir,
            args.output_dir,
            weights=args.weights
        )
        print(f"Processing {'successful' if status else 'failed'}")
    except Exception as e:
        print(f"Error processing files: {e}")

```

2025-02-11 15:19 UTC, tnelson-integral commented on seat/paracousti_pre_process_routine.py
> +save_directory = r"C:\Users\aellenson\OneDrive - Integral Consulting Inc\C1308 Sandia\Tutorial_Files\Development\DEMO Files Tabbed GUI - Acoustics\pacwave\paracousti_files_with_metrics_TU\\"
That sounds like a great idea. I like the code. I must have missed this before but let's make the default 'LFC' as opposed to 'TU'.

2025-02-12 15:22 UTC, ssolson commented on seat/stressor_receptor_calc.py
> +        root = QgsProject.instance().layerTreeRoot()
@tnelson-integral this root definition is overwriting any root passed to the function should this be:

```
        if root is None:
            root = QgsProject.instance().layerTreeRoot()
```

2025-02-12 19:12 UTC, ssolson commented
@tnelson-integral can you review and if everything looks good to you merge https://github.com/IntegralEnvision/seat-qgis-plugin/pull/18 so that all the tests on this PR will pass.

2025-02-13 19:13 UTC, tnelson-integral commented
Hi Sterling,
I will go through this and get back to you once I verify everything works on my end.
-Thanks,
-Tim


Tim Nelson (he/him/his) | Senior Scientist
Tel: 561.240.5096 | Cell: 803.319.3344 | St. Petersburg | FL
***@***.*** | Bio<https://www.integral-corp.com/staff/timothy-r-nelson-ph-d>

<https://www.integral-corp.com/>[cid:integral_1a04a855-2877-4c4f-bd98-b89de3950d0f.png]<https://www.integral-corp.com/>

________________________________
From: ssolson ***@***.***>
Sent: Wednesday, February 12, 2025 2:12 PM
To: sandialabs/seat-qgis-plugin ***@***.***>
Cc: Tim Nelson ***@***.***>; Mention ***@***.***>
Subject: Re: [sandialabs/seat-qgis-plugin] Acoustics module update (PR #34)

[CAUTION: External email. Think before you click links or open attachments.]

@tnelson-integral<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tnelson-2Dintegral&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=VA9fFwnM40rQ_NzOfxzb3KKsMTw_iTeb0ZmvbAzMcyFdpliuYGqHhOqXNVPL2TxI&s=CoVIMvHhUmmEJsG-z1R-gaNZZb976v-2AFTkte5kDmg&e=> can you review and if everything looks good to you merge IntegralEnvision#18<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IntegralEnvision_seat-2Dqgis-2Dplugin_pull_18&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=VA9fFwnM40rQ_NzOfxzb3KKsMTw_iTeb0ZmvbAzMcyFdpliuYGqHhOqXNVPL2TxI&s=uAGEAZwkzhIKZFNqhIJ-h3NVx3GEA7AGlhYsSmWq8GY&e=> so that all the tests on this PR will pass.

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sandialabs_seat-2Dqgis-2Dplugin_pull_34-23issuecomment-2D2654623814&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=VA9fFwnM40rQ_NzOfxzb3KKsMTw_iTeb0ZmvbAzMcyFdpliuYGqHhOqXNVPL2TxI&s=uZRDZl4jcqi7fyHm5_U7HmOjpEj2j2XMantjO7-rOEM&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AZARDBK6NLP7643YWABPF7T2POMKFAVCNFSM6AAAAABJ6TD5U2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMNJUGYZDGOBRGQ&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=VA9fFwnM40rQ_NzOfxzb3KKsMTw_iTeb0ZmvbAzMcyFdpliuYGqHhOqXNVPL2TxI&s=EQ1YJxcM2ck_qx_Ph-N1LPJ077RJtmAHXpqRSODuFt0&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

[https://avatars.githubusercontent.com/u/13438942?s=20&v=4]ssolson left a comment (sandialabs/seat-qgis-plugin#34)<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sandialabs_seat-2Dqgis-2Dplugin_pull_34-23issuecomment-2D2654623814&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=VA9fFwnM40rQ_NzOfxzb3KKsMTw_iTeb0ZmvbAzMcyFdpliuYGqHhOqXNVPL2TxI&s=uZRDZl4jcqi7fyHm5_U7HmOjpEj2j2XMantjO7-rOEM&e=>

@tnelson-integral<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tnelson-2Dintegral&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=VA9fFwnM40rQ_NzOfxzb3KKsMTw_iTeb0ZmvbAzMcyFdpliuYGqHhOqXNVPL2TxI&s=CoVIMvHhUmmEJsG-z1R-gaNZZb976v-2AFTkte5kDmg&e=> can you review and if everything looks good to you merge IntegralEnvision#18<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IntegralEnvision_seat-2Dqgis-2Dplugin_pull_18&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=VA9fFwnM40rQ_NzOfxzb3KKsMTw_iTeb0ZmvbAzMcyFdpliuYGqHhOqXNVPL2TxI&s=uAGEAZwkzhIKZFNqhIJ-h3NVx3GEA7AGlhYsSmWq8GY&e=> so that all the tests on this PR will pass.

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sandialabs_seat-2Dqgis-2Dplugin_pull_34-23issuecomment-2D2654623814&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=VA9fFwnM40rQ_NzOfxzb3KKsMTw_iTeb0ZmvbAzMcyFdpliuYGqHhOqXNVPL2TxI&s=uZRDZl4jcqi7fyHm5_U7HmOjpEj2j2XMantjO7-rOEM&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AZARDBK6NLP7643YWABPF7T2POMKFAVCNFSM6AAAAABJ6TD5U2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMNJUGYZDGOBRGQ&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=2OT5Kb-Guh1vdHPYH_OKgQqqKZs-WcstcKgpghDlHN8&m=VA9fFwnM40rQ_NzOfxzb3KKsMTw_iTeb0ZmvbAzMcyFdpliuYGqHhOqXNVPL2TxI&s=EQ1YJxcM2ck_qx_Ph-N1LPJ077RJtmAHXpqRSODuFt0&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2025-02-28 19:11 UTC, ssolson approved these changes
Thanks Tim. The code is now passing all tests. 

More revisions are needed to the documentation but I leave that work to Cesar in a follow on PR.

2025-02-28 19:13 UTC, merged